### ISSUE TITLE
1.21.3/4 update

### ISSUE THREAD

**Issue by adr278** [girlbossdev/LogarithmicVolumeControl#2]
mod needs an update

**Comment by girlbossdev** [comment]
I'm very late to this, but the mod does still work fine on the latest version without any changes. I did forget to update the Modrinth page though, so I'll do that now.

**Comment by adr278** [comment]
> I'm very late to this, but the mod does still work fine on the latest version without any changes. I did forget to update the Modrinth page though, so I'll do that now.

I noticed that it still works like, 3 or so days ago lol
but tysm! love your mod ❤
